version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - SQL_QUERY_MANAGER_SECRET_KEY=your-secret-key
      - DATABASE_URL="sqlite:///data/sql_query_manager.db"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 